# Generated by Django 4.1.5 on 2023-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
