# Generated by Django 4.1.5 on 2023-02-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_order_amount_order_order_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shippingAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Deliverd', 'Deliverd')], max_length=50),
        ),
    ]
