# Generated by Django 4.1.7 on 2023-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='State',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
