# Generated by Django 4.1.7 on 2023-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_order_address_order_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Deliverd', 'Deliverd')], max_length=50),
        ),
    ]
