# Generated by Django 4.1.7 on 2023-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_trackingId',
            field=models.CharField(default='Awaiting Shipping', max_length=50, null=True),
        ),
    ]
