# Generated by Django 4.1.7 on 2023-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_order_order_trackingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Shipped', 'Shipped'), ('Deliverd', 'Deliverd')], max_length=50),
        ),
    ]
