# Generated by Django 4.1.7 on 2023-03-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_deliveryState',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
